### ISSUE TITLE
Possible to use syslog?

### ISSUE THREAD

**Issue by jg-development** [stefanprodan/dockelk#3]
Hi,
I want to use a syslog solution from the nginx servers. Is this possible?
Like this
```
access_log            syslog:server=127.0.0.1:12201 internal;
```
I know this cannot work but do you have a config for the shipper with a direct input from a syslog?
Not all our projects are in docker containers, so we need a solution with an udp syslog.
Any ideas?
Greetings Jan

**Comment by stefanprodan** [comment]
You can configure the Logstash shipper to expose a syslog endpoint, here https://www.elastic.co/guide/en/logstash/2.4/plugins-inputs-syslog.html

**Comment by jg-development** [comment]
Hi,
thanks for the hint, but yesterday I switched all to gelf ;-)
